yuma = ("N47198", "NAVMEDREADTRNUNIT YUMA AZ")
cpen = ("N68094", "NMRTC CAMP PENDLETON CA")
ctrs = ("NKTR00", "CONTRACTOR REPORTING")
reports={
    "ASPE-1.0": "ACTIVE SHOOTER PRACTICAL EXERCISE",
    "CDSE-INSIDER-1.0": "INSIDER THREAT AWARENESS",
    "CENSECFOR-AT-010-2.0": "ANTI-TERRORISM LEVEL 1 AWARENESS TRAINING",
    "CPPD-GMT-SAP-1.0": "SUICIDE AWARENESS AND PREVENTION",
    "CPPD-GMT-SAPRA-1.0": "SEXUAL ASSAULT PREVENTION AND RESPONSE AWARENESS",
    "DHA-US001": "HIPAA AND PRIVACY ACT TRAINING",
    "DHA-US466": "NAVY MEDICINE OFF DUTY EMPLOYMENT (MOONLIGHTING) ANNUAL TRAINING",
    "DHA-US467": "NAVY MEDICINE PREVENTION OF UNAUTHORIZED COMMITMENTS (UAC)",
    "DOD-CAC-2022.0": "CYBER AWARENESS CHALLENGE 2022",
    "DOD-CTIP-5.0": "COMBATING TRAFFICKING IN PERSONS",
    "DON-687121-1.0": "DON ACTIVE SHOOTER",
    "DON-CIAR-1.0": "NCIS COUNTERINTELLIGENCE AND INSIDER THREAT AWARENESS AND REPORTING TRAINING",
    "DON-PRIV-2.0": "DEPARTMENT OF THE NAVY ANNUAL PRIVACY TRAINING",
    "NOST-USOPSEC-4.0": "NAVY SUICIDE PREVENTION TRAINING FOR PROVIDERS (UNCLASSIFIED-FOUO)(RS)",
    "DHA-US1146": "CONSTITUTION DAY AWARENESS",
    "DHA-US1159": "DHA WORKPLACE SAFETY",
    "DHA-US323": "MHS CUSTOMER SERVICE",
    "DHA-US429": "RECORDS MANAGEMENT IN THE DON: EVERYONE'S RESPONSIBILITY",
    "DOR-RM-010-1.2": "USOPSEC/IDM",
}